var aNavDateList = [
	[
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}
	],

	[
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}
	],

	[
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}
	],

	[
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}
	],

	[
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}
	],	

	[
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}
	],

	[
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}
	],

	[
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'4100',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com',
			src:'images/p1.jpg',
			name:'小米MX3',
			price:'3299',
			tag:'新品'
		}
	],


]

var aLoadCadeList = [
	[
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小1'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米11'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米11'
		},
	],

	[
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],

	[
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],

	[
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],

	[
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],

	[
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],

	[
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],

	[
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],

	[
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],

	[
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],
]